export enum ApiKnownErrorResType {
  INVALID_CREDENTIALS = 'INVALID_CREDENTIALS',
  EXISTING_USERNAME = 'EXISTING_USERNAME',
  EXISTING_EMAIL = 'EXISTING_EMAIL',
  INVITE_ALREADY_EXISTS = 'INVITE_ALREADY_EXISTS',
}

export interface ApiErrorRes {
  type: ApiKnownErrorResType;
}
